import type React from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    minHeight: '100vh',
    minWidth: '100vw',
    backgroundColor: '#f9fafb',
    padding: '2rem',
  },
  content: {
    width: '100%',
    maxWidth: '1400px',
    margin: '0 auto',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)',
    padding: '24px',
    marginTop: '24px',
    marginBottom: '24px',
  },
  title: {
    fontSize: '30px',
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: '24px',
    marginTop: 0,
  },
  navigation: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '24px',
  },
  navButton: {
    padding: '8px',
    backgroundColor: 'transparent',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    fontSize: '32px',
    fontWeight: 'bold',
    lineHeight: '1',
    color: 'black',
  },
  icon: {
    width: '24px',
    height: '24px',
  },
  smallIcon: {
    width: '16px',
    height: '16px',
  },
  monthTitle: {
    fontSize: '24px',
    fontWeight: '600',
    color: '#1f2937',
    margin: 0,
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '16px',
    marginBottom: '24px',
  },
  statCard: {
    backgroundColor: '#f9fafb',
    padding: '16px',
    borderRadius: '8px',
  },
  statLabel: {
    fontSize: '12px',
    color: '#6b7280',
    marginBottom: '4px',
  },
  statValue: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: '#1f2937',
  },
  calendar: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: '4px',
  },
  weekdayHeader: {
    textAlign: 'center',
    fontSize: '14px',
    fontWeight: '600',
    color: '#4b5563',
    padding: '8px',
  },
  emptyCell: {
    aspectRatio: '1',
  },
  dayCell: {
    aspectRatio: '1',
    border: '1px solid #e5e7eb',
    padding: '8px',
    display: 'flex',
    flexDirection: 'column',
  },
  todayCell: {
    boxShadow: '0 0 0 2px #3b82f6',
  },
  activeDayCell: {
    cursor: 'pointer',
  },
  dayNumber: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#374151',
    marginBottom: '4px',
  },
  dayContent: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  profitText: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#16a34a',
  },
  lossText: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#dc2626',
  },
  tradesText: {
    fontSize: '12px',
    color: '#6b7280',
    marginTop: '4px',
  },
  legend: {
    marginTop: '24px',
    display: 'flex',
    alignItems: 'center',
    gap: '24px',
    fontSize: '14px',
  },
  legendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  legendBox: {
    width: '16px',
    height: '16px',
    borderRadius: '2px',
  },
  legendText: {
    color: '#4b5563',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
  },
  modal: {
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    padding: '24px',
    maxWidth: '400px',
    width: '90%',
    boxShadow: '0 10px 25px rgba(0, 0, 0, 0.2)',
  },
  modalTitle: {
    fontSize: '20px',
    fontWeight: 'bold',
    marginTop: 0,
    marginBottom: '20px',
    color: '#1f2937',
  },
  formGroup: {
    marginBottom: '16px',
  },
  label: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '500',
    marginBottom: '6px',
    color: '#374151',
  },
  input: {
    width: '100%',
    padding: '8px 12px',
    fontSize: '14px',
    border: '1px solid #d1d5db',
    borderRadius: '6px',
    boxSizing: 'border-box',
  },
  modalButtons: {
    display: 'flex',
    gap: '8px',
    marginTop: '20px',
  },
  submitButton: {
    flex: 1,
    padding: '10px 16px',
    backgroundColor: '#3b82f6',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  deleteButton: {
    flex: 1,
    padding: '10px 16px',
    backgroundColor: '#dc2626',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  cancelButton: {
    flex: 1,
    padding: '10px 16px',
    backgroundColor: '#6b7280',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  goalSection: {
    backgroundColor: '#f0f9ff',
    padding: '20px',
    borderRadius: '8px',
    marginBottom: '24px',
    border: '2px solid #3b82f6',
  },
  goalTitle: {
    fontSize: '18px',
    fontWeight: '600',
    color: '#1f2937',
    marginTop: 0,
    marginBottom: '16px',
  },
  setGoalButton: {
    width: '100%',
    padding: '16px',
    backgroundColor: '#3b82f6',
    color: '#ffffff',
    border: 'none',
    borderRadius: '8px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    marginBottom: '24px',
    transition: 'background-color 0.2s',
  },
  goalForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  goalInput: {
    padding: '12px',
    fontSize: '16px',
    border: '2px solid #3b82f6',
    borderRadius: '6px',
    outline: 'none',
  },
  goalFormButtons: {
    display: 'flex',
    gap: '8px',
  },
  goalSaveButton: {
    flex: 1,
    padding: '10px 16px',
    backgroundColor: '#16a34a',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  goalCancelButton: {
    flex: 1,
    padding: '10px 16px',
    backgroundColor: '#6b7280',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  goalStats: {
    display: 'flex',
    justifyContent: 'space-around',
    marginBottom: '16px',
    flexWrap: 'wrap',
    gap: '12px',
  },
  goalStatItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  goalLabel: {
    fontSize: '12px',
    color: '#6b7280',
    marginBottom: '4px',
  },
  goalValue: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#1f2937',
  },
  progressBarContainer: {
    width: '100%',
    height: '24px',
    backgroundColor: '#e5e7eb',
    borderRadius: '12px',
    overflow: 'hidden',
    marginBottom: '8px',
  },
  progressBar: {
    height: '100%',
    transition: 'width 0.3s ease, background-color 0.3s ease',
    borderRadius: '12px',
  },
  progressText: {
    textAlign: 'center',
    fontSize: '14px',
    color: '#4b5563',
    marginBottom: '16px',
  },
  goalActions: {
    display: 'flex',
    gap: '8px',
  },
  editGoalButton: {
    flex: 1,
    padding: '8px 16px',
    backgroundColor: '#3b82f6',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
  },
  clearGoalButton: {
    flex: 1,
    padding: '8px 16px',
    backgroundColor: '#dc2626',
    color: '#ffffff',
    border: 'none',
    borderRadius: '6px',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
  },
};


